# Generated by Django 5.2 on 2025-04-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Balochistan', 'Balochistan'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('Islamabad Capital Territory', 'Islamabad Capital Territory'), ('Azad Jammu and Kashmir', 'Azad Jammu and Kashmir'), ('Gilgit-Baltistan', 'Gilgit-Baltistan')], max_length=50),
        ),
    ]
